export var FLAVOR_GROUPS = [
  { id: '情绪基调', label: '情绪基调' },
  { id: '关系动态', label: '关系动态' },
  { id: '心理心智', label: '心理心智' },
  { id: '身体受控', label: '身体受控' },
  { id: '角色仪式', label: '角色仪式' },
  { id: '感官节奏', label: '感官节奏' },
  { id: '异质物质', label: '异质物质' },
  { id: '成瘾心理', label: '成瘾心理' },
  { id: '形貌变身', label: '形貌变身' },
  { id: '超自然接触', label: '超自然接触' },
  { id: '机械赛博', label: '机械赛博' },
  { id: '迷幻药物', label: '迷幻药物' },
  { id: '表演仪式', label: '表演仪式' },
  { id: '场景环境', label: '场景环境' },
  { id: '群体动态', label: '群体动态' },
];
