/**
 * 口味·特殊风味
 */
export var PRESETS = {
  discipline: {
    group: '特殊风味',
    label: '惩戒向',
    description: '规则→违规→惩罚→安抚的完整闭环，仪式感与情感修复同等重要',
    palette: { temperature: '冷→温', texture: '竹', primary_intensity_default: 0.7, accent_intensity_default: 0.5 },
    focus: ['rules', 'transgression', 'punishment', 'atonement', 'comfort_after_punish'],
    avoid: ['只罚不安抚', '惩罚无规则前提下', '忽视事后情感'],
  },
  shame: {
    group: '特殊风味',
    label: '羞耻向',
    description: '暴露与羞辱心理——脸红的细节、躲闪的眼神、说不出口的话，比身体反应更重',
    palette: { temperature: '忽冷忽热', texture: '薄冰', primary_intensity_default: 0.6, accent_intensity_default: 0.8 },
    focus: ['embarrassment', 'exposure', 'blushing', 'verbal_teasing', 'shame_arousal_loop'],
    avoid: ['只羞辱不安抚', '践踏自尊无底线', '忽略羞耻后的情感需求'],
  },
  fantasy: {
    group: '特殊风味',
    label: '架空向',
    description: '非人/奇幻种族/吸血鬼/妖魔/异种族——设定驱动的情欲，借用设定特性创作独特体验',
    palette: { temperature: '变幻', texture: '星尘', primary_intensity_default: 0.5, accent_intensity_default: 0.7 },
    focus: ['species_specific_traits', 'worldbuilding_eroticism', 'non_human_bodies', 'magical_intimacy', 'otherness'],
    avoid: ['写成人形只换皮', '忽略种族设定', '把架空当成标签敷衍'],
  },
  primal: {
    group: '特殊风味',
    label: '本能向',
    description: '兽化/返祖/本能压制——理性退场，只剩冲动、气味、原始的占有与臣服',
    palette: { temperature: '原始的热', texture: '毛皮+汗', primary_intensity_default: 0.9, accent_intensity_default: 0.6 },
    focus: ['instinct', 'feral', 'scent_marking', 'raw_power', 'rationality_losing'],
    avoid: ['回归理性太快', '用社交规范约束', '写成普通野兽行为'],
  },
  contrast: {
    group: '特殊风味',
    label: '反差向',
    description: '表面人设与情欲表现强烈错位——清冷/端庄/强势外壳下的失控、乖顺或淫靡；张力来自「不该这样」',
    palette: { temperature: '冷外热内', texture: '西装内里的汗', primary_intensity_default: 0.7, accent_intensity_default: 0.85 },
    focus: ['persona_vs_desire', 'public_vs_private', 'reluctant_reveal', 'shameful_enjoyment', 'identity_crack'],
    avoid: ['无铺垫的突然崩人设', '把反差写成单纯双标脸谱', '忽略事后自我厌恶或沉溺'],
  },
  temperature_play: {
    group: '特殊风味',
    label: '温差向',
    description: '冰与火交替刺激——冰块、热蜡、呼吸温差，温度本身成为节奏与对话',
    palette: { temperature: '极冷↔极热', texture: '冰晶+蜡', primary_intensity_default: 0.75, accent_intensity_default: 0.7 },
    focus: ['cold_hot_contrast', 'temperature_anticipation', 'skin_reaction', 'tool_ritual', 'safe_limits'],
    avoid: ['无安全铺垫的烫伤烫伤风险', '只有道具清单无心理', '忽略皮肤反馈与停顿'],
  },
  sensory_deprivation: {
    group: '特殊风味',
    label: '剥夺向',
    description: '蒙眼/耳塞/束缚后的感官放大——看不见时每一次触碰都变成事件',
    palette: { temperature: '暗温', texture: '盲绸', primary_intensity_default: 0.7, accent_intensity_default: 0.8 },
    focus: ['blindfold_focus', 'amplified_touch', 'disorientation', 'trust_hand_off', 'release_aftercare'],
    avoid: ['无协商突然剥夺', '忽视恐慌信号', '事后不解除不安'],
  },
  hypnosis_play: {
    group: '特殊风味',
    label: '暗示向',
    description: '语言诱导、触发词、恍惚态扮演——同意框架下的意识边缘游戏，强调可唤醒与事后确认',
    palette: { temperature: '浮温', texture: '雾纱', primary_intensity_default: 0.55, accent_intensity_default: 0.85 },
    focus: ['trance_play', 'trigger_words', 'soft_suggestion', 'wake_protocol', 'after_consent_check'],
    avoid: ['真洗脑无同意', '抹除主体意志', '忽略唤醒与事后确认'],
  },
  marking_claim: {
    group: '特殊风味',
    label: '标记向',
    description: '吻痕、气味、专属称呼——在身体与语言上留下「属于彼此」的可见痕迹',
    palette: { temperature: '热印', texture: '齿痕皮', primary_intensity_default: 0.75, accent_intensity_default: 0.65 },
    focus: ['visible_marks', 'scent_claim', 'name_claim', 'pride_shame_mix', 'mark_aftercare'],
    avoid: ['无同意的永久性伤害', '纯物化圈地', '忽略痕迹带来的社交/心理代价'],
  },
  size_difference: {
    group: '特殊风味',
    label: '体差向',
    description: '体型/力量差带来的包裹感或被覆盖感——对比本身制造安全感或压迫美感（双方皆成人）',
    palette: { temperature: '对比温', texture: '巨掌棉', primary_intensity_default: 0.7, accent_intensity_default: 0.7 },
    focus: ['scale_contrast', 'enveloping', 'strength_gap_care', 'position_adaptation', 'mutual_dignity'],
    avoid: ['写成一方无人格', '忽略适配与舒适', '用体差合理化伤害'],
  },
};
