/**
 * 扩展世界观框架 + 丰满规范
 * matriarchy court pirate wasteland idol_industry medical mecha honghuang
 */

export var FRAMES = {
  matriarchy: {
    id: 'matriarchy',
    label: '女尊',
    lexicon: ['女君', '男妃', '女尊', '坤道', '乾务', '赐婚', '宗嗣', '内宅', '诰命', '女官', '男德', '侍寝', '侧室'],
    antiLexicon: ['父权家法当唯一秩序', '义体', '飞船权限', '异能协会'],
    signals: ['女尊', '女君', '男妃', '坤道', '赐婚', '男德', '女官', '内宅', '诰命', '宗嗣'],
    vesselSeeds: [
      { kind: 'artifact', nameHint: '赐婚玉佩/锁心镯/侍寝令牌' },
      { kind: 'rule', nameHint: '女君家法/男妃侍寝条例' },
      { kind: 'place', nameHint: '内宅暖阁/女君寝殿侧室' },
      { kind: 'ritual', nameHint: '纳妃礼/验身契约' },
      { kind: 'org', nameHint: '女官署/内廷监察' },
      { kind: 'substance', nameHint: '安神汤/固本丹（公开名义）' },
    ],
  },
  court: {
    id: 'court',
    label: '宫廷',
    lexicon: ['宫墙', '御前', '嫔妃', '宦官', '密折', '赐药', '冷宫', '仪仗', '旨意', '后宫', '太监', '凤印', '夜值'],
    antiLexicon: ['灵根', '异能评级', '义体接口', '社团活动室'],
    signals: ['宫廷', '后宫', '皇帝', '嫔妃', '御前', '密折', '冷宫', '宫女', '太监', '龙床'],
    vesselSeeds: [
      { kind: 'artifact', nameHint: '凤印信物/夜值腰牌/密折匣' },
      { kind: 'place', nameHint: '偏殿暖阁/冷宫暗室/御花园僻径' },
      { kind: 'rule', nameHint: '侍寝制度/宫规禁足' },
      { kind: 'substance', nameHint: '赐药/安神香/绝子散' },
      { kind: 'org', nameHint: '内廷司/东厂式暗线' },
      { kind: 'ritual', nameHint: '册封礼/侍夜仪轨' },
    ],
  },
  pirate: {
    id: 'pirate',
    label: '海盗海域',
    lexicon: ['甲板', '船舱', '海图', '黑旗', '分赃', '俘虏', '潮汐', '暗礁', '船长令', '私掠', '港口', '缆绳', '酒窖'],
    antiLexicon: ['宗门戒律', '异能协会', '脑机协议', '校规'],
    signals: ['海盗', '海域', '甲板', '船长', '私掠', '黑旗', '海战', '俘虏', '港口', '航海'],
    vesselSeeds: [
      { kind: 'place', nameHint: '船长舱/底舱禁闭室/无人礁岛' },
      { kind: 'artifact', nameHint: '镣铐/航海罗盘信物/分赃骰' },
      { kind: 'rule', nameHint: '船上规矩/俘虏归属条款' },
      { kind: 'org', nameHint: '海盗团/港口黑市商会' },
      { kind: 'substance', nameHint: '烈酒/迷药酒/创伤药膏' },
      { kind: 'ritual', nameHint: '入伙血誓/分赃夜宴' },
    ],
  },
  wasteland: {
    id: 'wasteland',
    label: '废土',
    lexicon: ['废土', '辐射', '避难所', '补给', '商队', '变异', '净化', '据点', '配额', '残骸', '过滤面罩', '黑市水'],
    antiLexicon: ['灵石飞剑', '宫廷仪仗', '脑机舱室', '学园祭'],
    signals: ['废土', '辐射', '避难所', '末日', '变异', '商队', '据点', '净化器', '残骸', '配额'],
    vesselSeeds: [
      { kind: 'artifact', nameHint: '净化项圈/配额手环/改装束缚带' },
      { kind: 'place', nameHint: '避难所隔离间/残骸掩体/水站暗室' },
      { kind: 'rule', nameHint: '据点生存配额/交易抵押条例' },
      { kind: 'substance', nameHint: '抗辐剂/迷幻尘/止痛针' },
      { kind: 'org', nameHint: '商队护卫/据点长老会' },
      { kind: 'ability', nameHint: '变异共感/辐射抗性共鸣' },
    ],
  },
  idol_industry: {
    id: 'idol_industry',
    label: '偶像娱乐',
    lexicon: ['经纪约', '舞台', '镜头', '通告', '粉丝', '练习室', '造型', '直播', '站位', '潜规则', '合同', '后台'],
    antiLexicon: ['法器灵力', '义体权限', '宗门戒律', '海盗分赃'],
    signals: ['偶像', '经纪', '舞台', '练习生', '通告', '粉丝', '直播', '选秀', '娱乐圈', '站位'],
    vesselSeeds: [
      { kind: 'artifact', nameHint: '麦架/耳返/造型束带/合同U盘' },
      { kind: 'place', nameHint: '练习室镜房/后台化妆间/保姆车' },
      { kind: 'rule', nameHint: '经纪合约漏洞/通告潜规则' },
      { kind: 'org', nameHint: '经纪公司/造型团队/黑粉公关' },
      { kind: 'ritual', nameHint: '出道仪式/粉丝见面暗号' },
      { kind: 'substance', nameHint: '提神剂/消肿针/妆前镇定喷雾' },
    ],
  },
  medical: {
    id: 'medical',
    label: '医疗',
    lexicon: ['病房', '病例', '麻醉', '监护', '医嘱', '隔离', '输液', '检查', '知情同意', '值班', '手术室', '药柜'],
    antiLexicon: ['双修阵', '飞剑', '黑旗分赃', '脑机舱'],
    signals: ['医院', '医生', '护士', '病房', '手术', '麻醉', '病例', '诊所', '医嘱', '监护仪'],
    vesselSeeds: [
      { kind: 'place', nameHint: '隔离病房/值班休息室/检查帘后' },
      { kind: 'artifact', nameHint: '约束带/监护电极/麻醉泵权限卡' },
      { kind: 'substance', nameHint: '镇静剂/诱导麻醉/外用药膏' },
      { kind: 'rule', nameHint: '知情同意书漏洞/值班交接条例' },
      { kind: 'org', nameHint: '专科治疗组/私密诊所' },
      { kind: 'ritual', nameHint: '术前确认仪式/复健协议' },
    ],
  },
  mecha: {
    id: 'mecha',
    label: '机甲军事',
    lexicon: ['机甲', '驾驶舱', '神经同步', '军规', '联合作战', '补给线', '代号', '座舱锁', '战损', '军衔', '装甲', '接口'],
    antiLexicon: ['合欢丹', '宫规侍寝', '社团钥匙', '咒物香火'],
    signals: ['机甲', '驾驶员', '神经同步', '军规', '战甲', '座舱', '军衔', '联合作战', '装甲', '补给'],
    vesselSeeds: [
      { kind: 'artifact', nameHint: '同步颈环/座舱束缚带/权限密钥' },
      { kind: 'place', nameHint: '机库暗间/双人驾驶舱/军医舱' },
      { kind: 'ability', nameHint: '神经同步过载/感官共享链路' },
      { kind: 'rule', nameHint: '军规处分/搭档强制同步条例' },
      { kind: 'org', nameHint: '特遣队/军械黑市' },
      { kind: 'substance', nameHint: '同步稳定剂/战损止痛剂' },
    ],
  },
  honghuang: {
    id: 'honghuang',
    label: '洪荒',
    lexicon: ['洪荒', '天道', '因果', '神通', '劫数', '道果', '本源', '先天灵宝', '气运', '圣威', '鸿蒙', '量劫'],
    antiLexicon: ['跳蛋', '酒店房卡', '异能协会评级', '经纪合约'],
    signals: ['洪荒', '天道', '因果', '神通', '劫数', '道果', '先天', '圣人', '气运', '量劫'],
    vesselSeeds: [
      { kind: 'artifact', nameHint: '先天锁灵宝/因果丝/道纹印' },
      { kind: 'ability', nameHint: '神通摄魂/双修道果共鸣' },
      { kind: 'ritual', nameHint: '渡劫双修阵/因果契约' },
      { kind: 'place', nameHint: '洞天禁地/鸿蒙秘境' },
      { kind: 'rule', nameHint: '天道戒律/圣门规矩' },
      { kind: 'substance', nameHint: '混沌丹/渡劫香' },
    ],
  },
};

export var ENRICHMENT = {
  matriarchy: {
    mustCover: [
      '女君/诰命体系下器物或条例如何生效',
      '男妃身份暴露或家法惩戒的代价',
      '公开场合的礼法伪装（赐婚/侍奉名义）',
      '至少一件赐婚信物或内宅规则载体',
      '与具名女君/男妃的不对等互动',
    ],
    writingGuide: '用女尊礼法写欲望：赐婚令、男德考核、内宅夜值。权力在女君侧，载体要体现制度而非单纯换性别外衣。',
    antiPatterns: ['写成普通现代恋爱换皮', '忽略礼法与宗嗣压力', '只有氛围没有女尊制度锚点'],
    densityHint: 350,
    signals: ['女君', '男妃', '赐婚', '内宅', '诰命', '侍寝'],
  },
  court: {
    mustCover: [
      '宫规/旨意/密折如何成为情欲载体机制',
      '被政敌或内廷发现的连锁代价',
      '仪仗/请安/赐药等公开名义伪装',
      '至少一处偏殿或信物级载体',
      '与具名帝后/嫔妃/内侍的权力关系',
    ],
    writingGuide: '涩感挂在宫墙与制度上：夜值腰牌、赐药、冷宫钥匙。每一件东西都要有「在宫里为何说得通」。',
    antiPatterns: ['无宫规的现代情趣清单', '忽略监视与密折风险', '只有华丽形容词'],
    densityHint: 350,
    signals: ['宫', '旨意', '密折', '侍寝', '赐', '冷宫'],
  },
  pirate: {
    mustCover: [
      '船上规矩/分赃/俘虏条款如何驱动亲密',
      '叛变、风暴或港口曝光的代价',
      '航海公务/伤员照料等表面借口',
      '至少一处船舱/礁岛或镣铐级载体',
      '与具名船长/水手/俘虏的从属关系',
    ],
    writingGuide: '用海域生存逻辑写欲望：甲板秩序、底舱禁闭、分赃夜。盐腥与绳索要进机制，不是奇幻法器换皮。',
    antiPatterns: ['突然出现法器灵力', '无船上规矩的纯浪漫', '忽略叛变与海难风险'],
    densityHint: 340,
    signals: ['甲板', '船舱', '俘虏', '分赃', '船长', '镣铐'],
  },
  wasteland: {
    mustCover: [
      '配额/净化/变异设定如何物化欲望机制',
      '辐射、补给断绝或据点驱逐风险',
      '医疗/交易/巡逻名义的伪装',
      '至少一件避难所器物或据点规则',
      '与具名商队/据点人的抵押或依附关系',
    ],
    writingGuide: '废土载体吃生存：水、药、配额手环、隔离间。欲望是稀缺资源交易的一部分。',
    antiPatterns: ['宫廷/修仙语汇错位', '无生存代价的纯氛围', '现代都市玩具清单'],
    densityHint: 340,
    signals: ['配额', '净化', '避难所', '辐射', '据点', '补给'],
  },
  idol_industry: {
    mustCover: [
      '经纪约/通告/镜头权限如何成为控制载体',
      '解约、黑料或粉丝反噬代价',
      '排练/造型/商务名义的社会伪装',
      '至少一处练习室/后台或合同级载体',
      '与具名经纪/搭档/制作人的不对等关系',
    ],
    writingGuide: '娱乐圈载体吃合同与镜头：耳返指令、镜房加班、通告捆绑。禁止写成无关的超自然道具。',
    antiPatterns: ['灵力法器错位', '无舆论/合同风险', '只有打歌无行业锚点'],
    densityHint: 340,
    signals: ['经纪', '合同', '练习室', '通告', '镜头', '后台'],
  },
  medical: {
    mustCover: [
      '医嘱/麻醉/监护协议的可触发机制',
      '医疗事故、投诉或执照风险',
      '治疗/复健/检查的正当名义',
      '至少一件医疗器物或病房规则',
      '与具名医患/护患的专业边界张力',
    ],
    writingGuide: '医疗载体必须像临床会存在的东西：约束带、泵权限、知情同意漏洞。专业术语进机制。',
    antiPatterns: ['无医疗逻辑的刑具清单', '忽略伦理与执照后果', '超自然法器硬套'],
    densityHint: 350,
    signals: ['医嘱', '麻醉', '监护', '病房', '知情同意', '约束'],
  },
  mecha: {
    mustCover: [
      '神经同步/座舱权限/军规如何驱动亲密',
      '战损、同步过载或军法处分代价',
      '训练/检修/战术研讨名义伪装',
      '至少一件同步器物或双人舱规则',
      '与具名驾驶员/指挥官的军衔关系',
    ],
    writingGuide: '机甲军事的涩感来自同步与军规：颈环校准、座舱锁、搭档强制链路。技术与军阶都要写进机制。',
    antiPatterns: ['修仙双修换皮', '无军规后果', '只有机甲外观无接口逻辑'],
    densityHint: 350,
    signals: ['同步', '座舱', '军规', '机甲', '权限', '战损'],
  },
  honghuang: {
    mustCover: [
      '天道/因果/神通/灵宝之一写出可运转机制',
      '劫数反噬或气运折损代价',
      '讲道/闭关/渡劫名义的公开伪装',
      '至少一件先天灵宝或因果契约载体',
      '与具名修士/圣嗣的道果或因果绑定',
    ],
    writingGuide: '洪荒用语写欲望：因果丝缚、神通摄魂、道果共鸣。格局要大，禁止写成普通修仙小法器堆砌。',
    antiPatterns: ['现代玩具名', '只有「很强很涩」无天道机制', '忽略劫数与因果代价'],
    densityHint: 360,
    signals: ['天道', '因果', '神通', '灵宝', '劫', '道果'],
  },
};
